import { Injectable } from '@nestjs/common';

type PlaceholderInput = {
  achievementType: string;
  levelCode?: string | null;
  projectId?: string | null;
};

@Injectable()
export class AchievementRecognitionService {
  generatePlaceholder(input: PlaceholderInput) {
    const ruleKey = `${input.achievementType}:${input.levelCode ?? 'UNSPECIFIED'}`;

    return {
      recognizedGrade: 'PENDING_RULE_CONFIG',
      scoreMapping: {
        configured: false,
        ruleKey,
        score: null,
        projectId: input.projectId ?? null,
        message: 'Recognition rules are not configured yet. Placeholder generated by service.',
      },
    };
  }
}
