export enum RoleCode {
  TEACHER = 'TEACHER',
  LAB_LEADER = 'LAB_LEADER',
  MINISTER = 'MINISTER',
  GROUP_LEADER = 'GROUP_LEADER',
  MEMBER = 'MEMBER',
  INTERN = 'INTERN',
}

export enum ResourceCode {
  AUTH = 'AUTH',
  SYSTEM = 'SYSTEM',
  ORG = 'ORG',
  MEMBER = 'MEMBER',
  APPROVAL = 'APPROVAL',
  INVENTORY = 'INVENTORY',
  DEVICE = 'DEVICE',
  DEVICE_REPAIR = 'DEVICE_REPAIR',
  COMPETITION = 'COMPETITION',
  COMPETITION_TEAM = 'COMPETITION_TEAM',
  ACHIEVEMENT = 'ACHIEVEMENT',
}

export enum ActionCode {
  VIEW = 'VIEW',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  EXECUTE = 'EXECUTE',
}

export enum DataScope {
  ALL = 'ALL',
  DEPT_PROJECT = 'DEPT_PROJECT',
  GROUP_PROJECT = 'GROUP_PROJECT',
  SELF_PARTICIPATE = 'SELF_PARTICIPATE',
}

export enum MenuCode {
  DASHBOARD = 'DASHBOARD',
  HEALTH = 'HEALTH',
  ORG_OVERVIEW = 'ORG_OVERVIEW',
  MEMBER_ARCHIVE = 'MEMBER_ARCHIVE',
  MEMBER_REGULARIZATION = 'MEMBER_REGULARIZATION',
  CONSUMABLE_LEDGER = 'CONSUMABLE_LEDGER',
  CONSUMABLE_REQUEST = 'CONSUMABLE_REQUEST',
  DEVICE_LEDGER = 'DEVICE_LEDGER',
  DEVICE_REPAIR = 'DEVICE_REPAIR',
  MEMBER_EXAMPLES = 'MEMBER_EXAMPLES',
  COMPETITION_LIBRARY = 'COMPETITION_LIBRARY',
  ACHIEVEMENT_LIST = 'ACHIEVEMENT_LIST',
  ACHIEVEMENT_ENTRY = 'ACHIEVEMENT_ENTRY',
  APPROVAL_CENTER = 'APPROVAL_CENTER',
  APPROVAL_DEMO = 'APPROVAL_DEMO',
}

export function buildPermissionCode(resource: ResourceCode, action: ActionCode) {
  return `${resource}:${action}` as const;
}

export const PermissionCodes = {
  authLogin: buildPermissionCode(ResourceCode.AUTH, ActionCode.EXECUTE),
  authSwitchRole: buildPermissionCode(ResourceCode.AUTH, ActionCode.UPDATE),
  authChangePassword: buildPermissionCode(ResourceCode.AUTH, ActionCode.UPDATE),
  systemDashboardView: buildPermissionCode(ResourceCode.SYSTEM, ActionCode.VIEW),
  systemHealthView: buildPermissionCode(ResourceCode.SYSTEM, ActionCode.VIEW),
  memberListView: buildPermissionCode(ResourceCode.MEMBER, ActionCode.VIEW),
  memberUpdate: buildPermissionCode(ResourceCode.MEMBER, ActionCode.UPDATE),
  memberCreate: buildPermissionCode(ResourceCode.MEMBER, ActionCode.CREATE),
  memberApprove: buildPermissionCode(ResourceCode.MEMBER, ActionCode.APPROVE),
  inventoryView: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.VIEW),
  inventoryCreate: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.CREATE),
  inventoryUpdate: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.UPDATE),
  inventoryApprove: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.APPROVE),
  deviceView: buildPermissionCode(ResourceCode.DEVICE, ActionCode.VIEW),
  deviceCreate: buildPermissionCode(ResourceCode.DEVICE, ActionCode.CREATE),
  deviceUpdate: buildPermissionCode(ResourceCode.DEVICE, ActionCode.UPDATE),
  deviceRepairView: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.VIEW),
  deviceRepairCreate: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.CREATE),
  deviceRepairUpdate: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.UPDATE),
  deviceRepairApprove: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.APPROVE),
  orgTreeView: buildPermissionCode(ResourceCode.ORG, ActionCode.VIEW),
  competitionView: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.VIEW),
  competitionCreate: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.CREATE),
  competitionUpdate: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.UPDATE),
  competitionRegistrationCreate: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.CREATE),
  competitionRegistrationUpdate: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.UPDATE),
  competitionRegistrationApprove: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.APPROVE),
  achievementView: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.VIEW),
  achievementCreate: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.CREATE),
  achievementUpdate: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.UPDATE),
  achievementApprove: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.APPROVE),
  approvalCenterView: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.VIEW),
  approvalCreate: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.CREATE),
  approvalApprove: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.APPROVE),
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];

const managementPermissions: PermissionCode[] = [
  PermissionCodes.inventoryView,
  PermissionCodes.inventoryCreate,
  PermissionCodes.inventoryUpdate,
  PermissionCodes.inventoryApprove,
  PermissionCodes.deviceView,
  PermissionCodes.deviceCreate,
  PermissionCodes.deviceUpdate,
  PermissionCodes.deviceRepairView,
  PermissionCodes.deviceRepairCreate,
  PermissionCodes.deviceRepairUpdate,
  PermissionCodes.deviceRepairApprove,
  PermissionCodes.competitionView,
  PermissionCodes.competitionCreate,
  PermissionCodes.competitionUpdate,
  PermissionCodes.competitionRegistrationCreate,
  PermissionCodes.competitionRegistrationUpdate,
  PermissionCodes.competitionRegistrationApprove,
  PermissionCodes.achievementView,
  PermissionCodes.achievementCreate,
  PermissionCodes.achievementUpdate,
  PermissionCodes.achievementApprove,
];

export const RolePermissionMap: Record<RoleCode, PermissionCode[]> = {
  [RoleCode.TEACHER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.systemHealthView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    PermissionCodes.orgTreeView,
    ...managementPermissions,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.LAB_LEADER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.systemHealthView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    PermissionCodes.orgTreeView,
    ...managementPermissions,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.MINISTER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    PermissionCodes.orgTreeView,
    ...managementPermissions,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.GROUP_LEADER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    PermissionCodes.orgTreeView,
    ...managementPermissions,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.MEMBER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberCreate,
    PermissionCodes.inventoryView,
    PermissionCodes.inventoryCreate,
    PermissionCodes.deviceView,
    PermissionCodes.deviceRepairView,
    PermissionCodes.deviceRepairCreate,
    PermissionCodes.competitionView,
    PermissionCodes.competitionRegistrationCreate,
    PermissionCodes.achievementView,
    PermissionCodes.achievementCreate,
    PermissionCodes.achievementUpdate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
  ],
  [RoleCode.INTERN]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberCreate,
    PermissionCodes.inventoryView,
    PermissionCodes.inventoryCreate,
    PermissionCodes.deviceView,
    PermissionCodes.deviceRepairView,
    PermissionCodes.deviceRepairCreate,
    PermissionCodes.competitionView,
    PermissionCodes.competitionRegistrationCreate,
    PermissionCodes.achievementView,
    PermissionCodes.achievementCreate,
    PermissionCodes.achievementUpdate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
  ],
};

export const RoleDataScopeMap: Record<RoleCode, DataScope> = {
  [RoleCode.TEACHER]: DataScope.ALL,
  [RoleCode.LAB_LEADER]: DataScope.ALL,
  [RoleCode.MINISTER]: DataScope.DEPT_PROJECT,
  [RoleCode.GROUP_LEADER]: DataScope.GROUP_PROJECT,
  [RoleCode.MEMBER]: DataScope.SELF_PARTICIPATE,
  [RoleCode.INTERN]: DataScope.SELF_PARTICIPATE,
};
