export enum RoleCode {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TEACHER = 'TEACHER',
  MINISTER = 'MINISTER',
  GROUP_LEADER = 'GROUP_LEADER',
  MEMBER = 'MEMBER',
  INTERN = 'INTERN',
}

export enum ResourceCode {
  AUTH = 'AUTH',
  PROFILE = 'PROFILE',
  NOTIFICATION = 'NOTIFICATION',
  CONFIG = 'CONFIG',
  SYSTEM = 'SYSTEM',
  ORG = 'ORG',
  MEMBER = 'MEMBER',
  EVALUATION = 'EVALUATION',
  PROMOTION = 'PROMOTION',
  APPROVAL = 'APPROVAL',
  INVENTORY = 'INVENTORY',
  FUND = 'FUND',
  DEVICE_LEDGER = 'DEVICE_LEDGER',
  DEVICE_REPAIR = 'DEVICE_REPAIR',
  COMPETITION = 'COMPETITION',
  COMPETITION_TEAM = 'COMPETITION_TEAM',
  ACHIEVEMENT = 'ACHIEVEMENT',
}

export enum ActionCode {
  VIEW = 'VIEW',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  EXECUTE = 'EXECUTE',
}

export enum DataScope {
  ALL = 'ALL',
  DEPT_PROJECT = 'DEPT_PROJECT',
  GROUP_PROJECT = 'GROUP_PROJECT',
  SELF_PARTICIPATE = 'SELF_PARTICIPATE',
}

export enum MenuCode {
  DASHBOARD = 'DASHBOARD',
  PROFILE = 'PROFILE',
  NOTIFICATIONS = 'NOTIFICATIONS',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
  HEALTH = 'HEALTH',
  ORG_OVERVIEW = 'ORG_OVERVIEW',
  MEMBER_ARCHIVE = 'MEMBER_ARCHIVE',
  MEMBER_REGULARIZATION = 'MEMBER_REGULARIZATION',
  EVALUATION_SCORE = 'EVALUATION_SCORE',
  PROMOTION_ELIGIBILITY = 'PROMOTION_ELIGIBILITY',
  PROMOTION_APPLICATION = 'PROMOTION_APPLICATION',
  CONSUMABLE_LEDGER = 'CONSUMABLE_LEDGER',
  CONSUMABLE_REQUEST = 'CONSUMABLE_REQUEST',
  DEVICE_REPAIR = 'DEVICE_REPAIR',
  FUND_OVERVIEW = 'FUND_OVERVIEW',
  FUND_APPLICATION = 'FUND_APPLICATION',
  COMPETITION_LIBRARY = 'COMPETITION_LIBRARY',
  ACHIEVEMENT_LIST = 'ACHIEVEMENT_LIST',
  ACHIEVEMENT_ENTRY = 'ACHIEVEMENT_ENTRY',
  APPROVAL_CENTER = 'APPROVAL_CENTER',
}

export function buildPermissionCode(resource: ResourceCode, action: ActionCode) {
  return `${resource}:${action}` as const;
}

export const PermissionCodes = {
  authLogin: buildPermissionCode(ResourceCode.AUTH, ActionCode.EXECUTE),
  authSwitchRole: buildPermissionCode(ResourceCode.AUTH, ActionCode.UPDATE),
  authChangePassword: buildPermissionCode(ResourceCode.AUTH, ActionCode.UPDATE),
  profileView: buildPermissionCode(ResourceCode.PROFILE, ActionCode.VIEW),
  notificationView: buildPermissionCode(ResourceCode.NOTIFICATION, ActionCode.VIEW),
  notificationUpdate: buildPermissionCode(ResourceCode.NOTIFICATION, ActionCode.UPDATE),
  systemDashboardView: buildPermissionCode(ResourceCode.SYSTEM, ActionCode.VIEW),
  systemHealthView: buildPermissionCode(ResourceCode.SYSTEM, ActionCode.VIEW),
  systemConfigView: buildPermissionCode(ResourceCode.CONFIG, ActionCode.VIEW),
  systemConfigUpdate: buildPermissionCode(ResourceCode.CONFIG, ActionCode.UPDATE),
  memberListView: buildPermissionCode(ResourceCode.MEMBER, ActionCode.VIEW),
  memberUpdate: buildPermissionCode(ResourceCode.MEMBER, ActionCode.UPDATE),
  memberCreate: buildPermissionCode(ResourceCode.MEMBER, ActionCode.CREATE),
  memberApprove: buildPermissionCode(ResourceCode.MEMBER, ActionCode.APPROVE),
  evaluationView: buildPermissionCode(ResourceCode.EVALUATION, ActionCode.VIEW),
  evaluationUpdate: buildPermissionCode(ResourceCode.EVALUATION, ActionCode.UPDATE),
  promotionView: buildPermissionCode(ResourceCode.PROMOTION, ActionCode.VIEW),
  promotionCreate: buildPermissionCode(ResourceCode.PROMOTION, ActionCode.CREATE),
  promotionUpdate: buildPermissionCode(ResourceCode.PROMOTION, ActionCode.UPDATE),
  promotionApprove: buildPermissionCode(ResourceCode.PROMOTION, ActionCode.APPROVE),
  inventoryView: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.VIEW),
  inventoryCreate: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.CREATE),
  inventoryUpdate: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.UPDATE),
  inventoryApprove: buildPermissionCode(ResourceCode.INVENTORY, ActionCode.APPROVE),
  fundView: buildPermissionCode(ResourceCode.FUND, ActionCode.VIEW),
  fundCreate: buildPermissionCode(ResourceCode.FUND, ActionCode.CREATE),
  fundUpdate: buildPermissionCode(ResourceCode.FUND, ActionCode.UPDATE),
  fundApprove: buildPermissionCode(ResourceCode.FUND, ActionCode.APPROVE),
  deviceLedgerCreate: buildPermissionCode(ResourceCode.DEVICE_LEDGER, ActionCode.CREATE),
  deviceRepairView: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.VIEW),
  deviceRepairCreate: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.CREATE),
  deviceRepairUpdate: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.UPDATE),
  deviceRepairApprove: buildPermissionCode(ResourceCode.DEVICE_REPAIR, ActionCode.APPROVE),
  orgTreeView: buildPermissionCode(ResourceCode.ORG, ActionCode.VIEW),
  competitionView: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.VIEW),
  competitionCreate: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.CREATE),
  competitionUpdate: buildPermissionCode(ResourceCode.COMPETITION, ActionCode.UPDATE),
  competitionRegistrationCreate: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.CREATE),
  competitionRegistrationUpdate: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.UPDATE),
  competitionRegistrationApprove: buildPermissionCode(ResourceCode.COMPETITION_TEAM, ActionCode.APPROVE),
  achievementView: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.VIEW),
  achievementCreate: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.CREATE),
  achievementUpdate: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.UPDATE),
  achievementApprove: buildPermissionCode(ResourceCode.ACHIEVEMENT, ActionCode.APPROVE),
  approvalCenterView: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.VIEW),
  approvalCreate: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.CREATE),
  approvalApprove: buildPermissionCode(ResourceCode.APPROVAL, ActionCode.APPROVE),
} as const;

export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes];

const managementPermissions: PermissionCode[] = [
  PermissionCodes.evaluationView,
  PermissionCodes.evaluationUpdate,
  PermissionCodes.promotionView,
  PermissionCodes.promotionCreate,
  PermissionCodes.promotionUpdate,
  PermissionCodes.promotionApprove,
  PermissionCodes.inventoryView,
  PermissionCodes.inventoryCreate,
  PermissionCodes.inventoryUpdate,
  PermissionCodes.inventoryApprove,
  PermissionCodes.deviceLedgerCreate,
  PermissionCodes.deviceRepairView,
  PermissionCodes.deviceRepairCreate,
  PermissionCodes.deviceRepairUpdate,
  PermissionCodes.deviceRepairApprove,
  PermissionCodes.competitionView,
  PermissionCodes.competitionCreate,
  PermissionCodes.competitionUpdate,
  PermissionCodes.competitionRegistrationCreate,
  PermissionCodes.competitionRegistrationUpdate,
  PermissionCodes.competitionRegistrationApprove,
  PermissionCodes.achievementView,
  PermissionCodes.achievementCreate,
  PermissionCodes.achievementUpdate,
  PermissionCodes.achievementApprove,
];

const groupLeaderManagementPermissions: PermissionCode[] = managementPermissions.filter(
  (permission) => permission !== PermissionCodes.competitionCreate,
);

export const RolePermissionMap: Record<RoleCode, PermissionCode[]> = {
  [RoleCode.SUPER_ADMIN]: Object.values(PermissionCodes) as PermissionCode[],
  [RoleCode.TEACHER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.profileView,
    PermissionCodes.notificationView,
    PermissionCodes.notificationUpdate,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.orgTreeView,
    PermissionCodes.promotionView,
    PermissionCodes.promotionApprove,
    PermissionCodes.fundView,
    PermissionCodes.fundCreate,
    PermissionCodes.fundUpdate,
    PermissionCodes.fundApprove,
    PermissionCodes.deviceRepairView,
    PermissionCodes.deviceRepairCreate,
    PermissionCodes.deviceLedgerCreate,
    PermissionCodes.competitionView,
    PermissionCodes.competitionCreate,
    PermissionCodes.competitionUpdate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.MINISTER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.profileView,
    PermissionCodes.notificationView,
    PermissionCodes.notificationUpdate,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    PermissionCodes.orgTreeView,
    PermissionCodes.fundView,
    PermissionCodes.fundCreate,
    PermissionCodes.fundUpdate,
    PermissionCodes.fundApprove,
    ...managementPermissions,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.GROUP_LEADER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.profileView,
    PermissionCodes.notificationView,
    PermissionCodes.notificationUpdate,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberUpdate,
    PermissionCodes.memberCreate,
    PermissionCodes.memberApprove,
    ...groupLeaderManagementPermissions,
    PermissionCodes.fundCreate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
    PermissionCodes.approvalApprove,
  ],
  [RoleCode.MEMBER]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.profileView,
    PermissionCodes.notificationView,
    PermissionCodes.notificationUpdate,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberCreate,
    PermissionCodes.evaluationView,
    PermissionCodes.promotionView,
    PermissionCodes.promotionCreate,
    PermissionCodes.inventoryView,
    PermissionCodes.inventoryCreate,
    PermissionCodes.deviceRepairView,
    PermissionCodes.deviceRepairCreate,
    PermissionCodes.competitionView,
    PermissionCodes.competitionRegistrationCreate,
    PermissionCodes.achievementView,
    PermissionCodes.achievementCreate,
    PermissionCodes.achievementUpdate,
    PermissionCodes.fundCreate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
  ],
  [RoleCode.INTERN]: [
    PermissionCodes.authLogin,
    PermissionCodes.authSwitchRole,
    PermissionCodes.authChangePassword,
    PermissionCodes.profileView,
    PermissionCodes.notificationView,
    PermissionCodes.notificationUpdate,
    PermissionCodes.systemDashboardView,
    PermissionCodes.memberListView,
    PermissionCodes.memberCreate,
    PermissionCodes.evaluationView,
    PermissionCodes.promotionView,
    PermissionCodes.promotionCreate,
    PermissionCodes.inventoryView,
    PermissionCodes.inventoryCreate,
    PermissionCodes.deviceRepairView,
    PermissionCodes.deviceRepairCreate,
    PermissionCodes.competitionView,
    PermissionCodes.competitionRegistrationCreate,
    PermissionCodes.achievementView,
    PermissionCodes.achievementCreate,
    PermissionCodes.achievementUpdate,
    PermissionCodes.fundCreate,
    PermissionCodes.approvalCenterView,
    PermissionCodes.approvalCreate,
  ],
};

export const RoleDataScopeMap: Record<RoleCode, DataScope> = {
  [RoleCode.SUPER_ADMIN]: DataScope.ALL,
  [RoleCode.TEACHER]: DataScope.ALL,
  [RoleCode.MINISTER]: DataScope.DEPT_PROJECT,
  [RoleCode.GROUP_LEADER]: DataScope.GROUP_PROJECT,
  [RoleCode.MEMBER]: DataScope.SELF_PARTICIPATE,
  [RoleCode.INTERN]: DataScope.SELF_PARTICIPATE,
};
